name: Acquire Unity License

on:
  workflow_dispatch:
    inputs:
      unity_email:
        description: 'Unity Email'
        required: true
        type: string
      unity_password:
        description: 'Unity Password'
        required: true
        type: string
      unity_serial:
        description: 'Unity Personal Serial Number'
        required: true
        type: string

jobs:
  activation:
    name: Generate Unity License Activation File
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-license-activate@v3
        id: activation
        with:
          unityVersion: 2022.3.20f1
          username: ${{ inputs.unity_email }}
          password: ${{ inputs.unity_password }}
          serial: ${{ inputs.unity_serial }}

      - uses: actions/upload-artifact@v4
        with:
          name: unity-license-activation
          path: ${{ steps.activation.outputs.licenseFilePath }}
